name: terraform information
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  pre-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
        shell: pwsh
      - run: .github/workflows/scripts/cleanup.ps1
        shell: pwsh
      - name: Commit deletion files
        continue-on-error: true
        run: |
          git config --global user.name 'Umar Khan'
          git config --global user.email 'umarkhan252@gmail.com'
          git add .
          git commit -m "Automated PS check in"
          git push

  ps-api-call-terraform:
    needs: pre-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
        shell: pwsh
      - name: terraform-api-calls
        shell: pwsh
        run: |
          .github/workflows/scripts/tfeworkspaces.ps1
        env:
          tfe_token: ${{ secrets.TFE_TOKEN }}
      - name: Commit Workspaces
        continue-on-error: true
        run: |
          git config --global user.name 'Umar Khan'
          git config --global user.email 'umarkhan252@gmail.com'
          git add .
          git commit -m "Automated PS check in"
          git push
  
  bash-api-call-terraform:
    needs: ps-api-call-terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: terraform-api-calls
        run: bash .github/workflows/scripts/tfworkspaces.sh
        env:
          tfe_token: ${{ secrets.TFE_TOKEN }}
      - name: Commit Workspaces Detailed Data
        continue-on-error: true
        run: |
          git config --global user.name 'Umar Khan'
          git config --global user.email 'umarkhan252@gmail.com'
          git add .
          git commit -m "Automated SH check in"
          git push
