name: terraform information
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  api-call-terraform:
    runs-on: internal-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: terraform-api-calls
        run: bash .github/workflows/scripts/tfworkspaces.sh
        env:
          tfe_token: ${{ secrets.TFE_TOKEN }}
          gh_token: ${{ secrets.GH_TOKEN }}
      - name: Commit report
        run: |
          git config --global user.name 'Umar Khan'
          git config --global user.email 'ukhan4@humana.com'
          git add .
          git commit -m "Automated check in"
          git push
